# service 
apiVersion: v1
kind: Service
metadata:  
  name: {{ .Values.fullname }}
spec:
  selector:
    name: {{ .Values.name }}
  ports:
  - protocol: TCP
    port: 80 # container or host or service
    targetPort: {{ .Values.targetport }} # ContainerPort 
  type: NodePort #ClusterIP, LoadBalancer, NodePort